import Ionicons from '@expo/vector-icons/Ionicons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { createOperationKey, harness, type HarnessAction } from '@/lib/harness';
import type { ActionInterfaceProps } from './types';

const allowedInFlow = (action: HarnessAction) => !action.id.startsWith('pos.') && !['flow.start', 'flow.publish', 'directory.install', 'directory.remove', 'record.update', 'task.complete'].includes(action.id);
const slug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80);

export default function FlowBuilderInterface(props: ActionInterfaceProps) {
  const insets = useSafeAreaInsets(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [available, setAvailable] = useState<HarnessAction[]>([]); const [selected, setSelected] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [operationKey] = useState(() => createOperationKey('flow.publish'));
  useEffect(() => { const timer = setTimeout(() => { void harness.registry().then((result) => setAvailable(result.actions.filter(allowedInFlow))).catch(() => setAvailable([])).finally(() => setLoading(false)); }, 0); return () => clearTimeout(timer); }, []);
  const add = (id: string) => setSelected((current) => [...current, id]);
  const remove = (index: number) => setSelected((current) => current.filter((_, itemIndex) => itemIndex !== index));
  const publish = async () => { const botId = typeof props.initialInput?.botId === 'string' ? slug(props.initialInput.botId) : ''; const nameSlug = slug(name); const id = `custom.${botId}.${nameSlug}`; if (!botId || !nameSlug || !selected.length) { Alert.alert('Flow needs more information', 'Enter a name and choose at least one Action.'); return; } setSaving(true); try { const result = await harness.executeAction(props.scope, props.action.id, { botId, flowId: id, name: name.trim(), description: description.trim(), actions: selected.map((actionId) => ({ id: actionId })) }, operationKey); props.onSuccess(result); } catch (cause) { Alert.alert('Could not create Flow', cause instanceof Error ? cause.message : 'Try again.'); } finally { setSaving(false); } };
  return <Modal visible={props.visible} animationType="slide" presentationStyle="fullScreen" onRequestClose={props.onClose}><View style={[styles.page, { paddingTop: insets.top }]}><View style={styles.header}><TouchableOpacity style={styles.iconButton} onPress={props.onClose}><Ionicons name="close" size={26} color="#172033" /></TouchableOpacity><View style={styles.headerCopy}><Text style={styles.title}>Create custom Flow</Text><Text style={styles.subtitle}>{props.contextTitle || 'Choose Actions in the order they happen.'}</Text></View><TouchableOpacity disabled={saving} onPress={() => void publish()}>{saving ? <ActivityIndicator color="#172033" /> : <Text style={styles.create}>Create</Text>}</TouchableOpacity></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 28 }]} keyboardShouldPersistTaps="handled"><Text style={styles.label}>FLOW NAME</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="For example: New customer" style={styles.input} /><TextInput value={description} onChangeText={setDescription} placeholder="What outcome should this Flow produce?" multiline style={[styles.input, styles.description]} /><Text style={styles.label}>ACTION ORDER</Text>{selected.length ? <View style={styles.sequence}>{selected.map((id, index) => <View key={`${id}-${index}`} style={styles.sequenceRow}><Text style={styles.number}>{index + 1}</Text><Text style={styles.sequenceText}>{available.find((item) => item.id === id)?.title || id}</Text><TouchableOpacity onPress={() => remove(index)} accessibilityLabel={`Remove Action ${index + 1}`}><Ionicons name="close" size={19} color="#7b879a" /></TouchableOpacity></View>)}</View> : <Text style={styles.empty}>Tap Actions below to build the sequence.</Text>}<Text style={styles.label}>AVAILABLE ACTIONS</Text>{loading ? <ActivityIndicator color="#172033" /> : available.map((action) => <TouchableOpacity key={action.id} style={styles.actionRow} onPress={() => add(action.id)}><View style={styles.actionCopy}><Text style={styles.actionTitle}>{action.title}</Text><Text style={styles.actionDescription}>{action.description}</Text></View><Ionicons name="add-circle-outline" size={23} color="#68758c" /></TouchableOpacity>)}</ScrollView></View></Modal>;
}

const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#fff'},header:{minHeight:78,paddingHorizontal:12,paddingBottom:12,borderBottomWidth:1,borderColor:'#e3e7ef',flexDirection:'row',alignItems:'center',gap:8},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerCopy:{flex:1},title:{fontSize:19,fontWeight:'800',color:'#172033'},subtitle:{fontSize:12,color:'#68758c',marginTop:2},create:{fontSize:15,fontWeight:'800',color:'#172033',paddingHorizontal:10},content:{padding:24},label:{fontSize:11,fontWeight:'800',letterSpacing:1,color:'#7b879a',marginTop:20,marginBottom:8},input:{minHeight:52,borderWidth:1,borderColor:'#e3e7ef',borderRadius:12,paddingHorizontal:14,fontSize:16,color:'#172033',backgroundColor:'#f7f8fc'},description:{height:88,paddingTop:14,textAlignVertical:'top',marginTop:10},sequence:{borderWidth:1,borderColor:'#e3e7ef',borderRadius:14,overflow:'hidden'},sequenceRow:{minHeight:48,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#e3e7ef'},number:{width:22,fontSize:12,fontWeight:'800',color:'#7b879a'},sequenceText:{flex:1,fontSize:14,fontWeight:'700',color:'#172033'},empty:{fontSize:14,color:'#68758c',paddingVertical:8},actionRow:{minHeight:70,flexDirection:'row',alignItems:'center',gap:12,padding:12,borderWidth:1,borderColor:'#e3e7ef',borderRadius:14,marginBottom:9},actionCopy:{flex:1},actionTitle:{fontSize:15,fontWeight:'800',color:'#172033'},actionDescription:{fontSize:12,lineHeight:17,color:'#68758c',marginTop:2} });
