const $=s=>document.querySelector(s);

const flows={
channel:{owner:'Muthu · Owner',steps:[
['Message arrives','VERIFIED CHANNEL INGRESS','A customer says the delivered order contained the wrong item. The channel adapter verifies its signature, timestamp, account, and event ID before TAR treats it as a possible command.',['Customer message','Channel check','Command ledger'],'Untrusted text is now verified input. It still has no authority.','NEW MESSAGE','Priya','“Order #1042 had the wrong item.”','Reviewing source…','Verify message'],
['Run starts','DURABLE FLOW RUN','The Support Flow starts Run #811 and saves its checkpoint. The Runner receives one bounded step: understand the complaint and prepare a permitted next action.',['Verified input','Run #811','Runner'],'The Run remembers what happens next; the Queue only wakes it.','SUPPORT INBOX','Order #1042','Complaint linked to order','Run · investigating','Open work'],
['Context is built','PERMITTED CONTEXT RETRIEVAL','TAR loads the complaint, permitted Order fields, Payment status, the saved Run, and relevant tool results. Secrets and unrelated customer data are excluded.',['Tenant','Field policy','Context pack'],'Context supplies facts, never permission.','AGENT ACTIVITY','Context ready','Order facts + message','Private fields filtered','Inspect context'],
['Agent proposes','MODEL EXECUTOR INSIDE RUNNER','The LLM interprets the complaint and drafts a response plus a structured refund proposal. Its Skill supplies the method; its Tool allowlist permits reading the Order and proposing the registered refund Action.',['Skill + context','LLM','Schema check'],'The model may propose. It cannot refund or send by itself.','AGENT DRAFT','Suggested resolution','Refund ₹120 + reply draft','Needs owner approval','Review proposal'],
['Human decides','HUMAN WAIT + INBOX TASK','Policy requires an owner decision. TAR saves an approval Task with the exact amount, destination, Action version, and current Record version. Muthu reviews it in the app.',['Proposal','Approval Task','Owner decision'],'Approval binds this specific proposal; it is not a blank permission.','APPROVAL','Refund ₹120?','Order #1042 · Garlic bread','Response ready to send','Approve refund'],
['Gateway saves','ACTION GATEWAY + ATOMIC SAVE','After approval, TAR rechecks Muthu’s live access, the Order and Payment versions, and the refund rules. One transaction saves the refund, Run checkpoint, Events, and reply Effect Request.',['Approved Action','Gateway','Atomic save'],'The human decides; code and policy accept and save.','REFUND ACCEPTED','₹120 returned','Payment · partially refunded','Reply · waiting to send','View result'],
['External effect completes','EFFECT + EVENT + RUN COMPLETION','The effect worker sends the approved reply using a stable provider key. Its confirmed result appends an Event, wakes Run #811, and the Run completes. Unknown outcomes reconcile before retry.',['Effect Request','Provider result','Run completed'],'The external effect has its own durable lifecycle.','RESOLVED','Priya notified','Refund recorded','Run #811 · completed','Done']
]},
person:{owner:'You · My Agent',steps:[
['Person asks','PRIVATE INTENT','You ask My Agent to prepare a supplier follow-up. The request enters your private identity tenant.',['My Agent','Private tenant','Runner'],'A workspace owner cannot read this private conversation.','MY AGENT','Supplier follow-up','“Draft a message for mozzarella.”','Private task','Start'],
['Run starts','PRIVATE DURABLE RUN','A versioned Run stores the plan and next step so the task can pause, resume, or wait for you.',['Intent','Run checkpoint','Bounded step'],'Background work survives restarts without becoming unlimited work.','MY TASK','Draft supplier note','Run · active','Next · collect facts','Open'],
['Context is built','LIVE PERMISSION PROJECTION','The Runner loads your private instructions and only the Slice House stock fields your current membership permits.',['Private facts','Work projection','Context pack'],'My Agent gets your access, never extra access.','CONTEXT','Stock view allowed','Mozzarella · low','Supplier contact · permitted','Inspect'],
['Agent drafts','MODEL PROPOSAL','A writing Skill and the permitted facts guide the LLM. It returns a schema-checked draft and a proposed send Action.',['Skill','LLM','Draft + proposal'],'Drafting is reversible; sending is a separate controlled effect.','DRAFT READY','Supplier follow-up','Request 20 kg mozzarella','Not sent','Review message'],
['Human decides','SENSITIVE ACTION REVIEW','You review the exact recipient and message before sending.',['Draft','Your review','Approved Action'],'Your approval is attached to this recipient and this content.','REVIEW SEND','Fresh Foods','20 kg mozzarella request','Ready with your approval','Approve send'],
['Gateway saves','PRIVATE ACTION GATEWAY','TAR checks the connector permission and current authority, then saves an Effect Request and Run checkpoint together.',['Approved Action','Gateway','Effect Request'],'The model never receives database credentials or sends directly.','SENDING','Fresh Foods','Send request · pending','Run · waiting result','Track'],
['External effect completes','PROVIDER RESULT','The provider confirms the message. TAR records the result Event and completes the Run.',['Provider','Result Event','Run completed'],'If the outcome is unknown, TAR reconciles before retry.','SENT','Fresh Foods notified','Message · confirmed','Run · completed','Done']
]},
schedule:{owner:'TAR · Background work',steps:[
['Time arrives','DURABLE TIMER WAKE','At 09:00 the scheduler sends a stable Run ID. The timer asks TAR to inspect saved work; it does not decide what should happen.',['Schedule','Run ID','Queue wake'],'Turso holds the truth; the timer is only a doorbell.','FOLLOW-UP','Lead #302','Due now · 09:00','Run ready','Wake'],
['Run is claimed','FENCED LEASE','One worker claims the eligible Run using database time, version, owner, lease epoch, and expiry.',['Ready Run','Compare-and-set','Lease epoch'],'An expired older worker cannot commit after a replacement takes over.','BACKGROUND RUN','Claimed safely','Worker lease · active','Attempt 1','Inspect'],
['Context is built','RELOAD CURRENT FACTS','TAR loads the pinned Flow version, current lead, conversation, prior checkpoint, and today’s permission.',['Run + Flow','Live Records','Context pack'],'Yesterday’s plan cannot override today’s facts or access.','FOLLOW-UP','Lead #302','No reply for 3 days','Permission current','Prepare'],
['Agent drafts','BOUNDED MODEL STEP','The LLM drafts a follow-up using the published Skill and allowlisted read Tools. Turns, runtime, cost, retries, and stop condition are fixed.',['Context','LLM + Skill','Schema output'],'A looping or malformed model cannot run forever or become truth.','DRAFT READY','Lead #302','Follow-up prepared','Within limits','Review'],
['Human decides','HUMAN WAIT','If policy requires review, an Inbox Task captures the draft and the exact proposed send Action.',['Proposal','Inbox Task','Decision'],'A human wait is durable and resumes through the Gateway.','APPROVAL','Send follow-up?','Exact recipient + content','Awaiting decision','Approve'],
['Gateway saves','ACTION + EFFECT REQUEST','TAR rechecks the decision, current membership, connector, and Run version. It saves the next checkpoint, Event, and Effect Request atomically.',['Approval','Gateway','Atomic save'],'The external call happens after the request is durable.','QUEUED','Follow-up approved','Send request · pending','Run · waiting result','Track'],
['External effect completes','RESULT OR RECOVERY','A worker sends with a stable provider key. Confirmation completes the Run; transient failure retries; an ambiguous outcome stays unknown for reconciliation.',['Provider','Result Event','Complete / review'],'The system never calls an unknown outcome a success.','COMPLETED','Follow-up sent','History recorded','Run · completed','Done']
]}}
let scenario='channel',flowStep=0,mobileTab='inbox',selectedBot='pos';
const bots={pos:{name:'POS',label:'ORDER OPERATIONS',copy:'Accept Orders, track kitchen progress, take payment, and record handover.',tools:'pos.order.accept · pos.checkout'},support:{name:'Support',label:'CUSTOMER CARE',copy:'Turn a verified customer message into a safe, reviewable resolution.',tools:'orders.get · refund proposal'},stock:{name:'Stock watch',label:'INVENTORY',copy:'Monitors low stock and starts a follow-up only when the saved rule is due.',tools:'records.get · scheduled Run'},site:{name:'Site',label:'PUBLISHED PRESENCE',copy:'Keeps approved site content and published information in one controlled workspace.',tools:'records.get · publish Action'}};
function inboxMarkup(s){return `<p class="mock-kicker">${s[5]}</p><h3 class="mock-title">${s[6]}</h3><div class="mock-message"><b>${s[7]}</b>${s[8]}</div><div class="mock-card"><small>STATUS</small><b>${s[0]}</b><span>${s[4]}</span></div><div class="mock-action">${s[9]}</div>`}
function spaceMarkup(s){return `<p class="mock-kicker">SLICE HOUSE · SPACE</p><h3 class="mock-title">Today</h3><div class="mock-card accent"><small>ORDER IN PROGRESS</small><b>Order #1042</b><span>${s[0]} · ${s[4]}</span></div><div class="mock-card"><small>SALES TODAY</small><b>₹12,400</b><span>8 completed orders</span></div><div class="mock-card"><small>ATTENTION</small><b>1 kitchen task</b><span>Open Inbox to continue work</span></div>`}
function botsMarkup(){const bot=bots[selectedBot];return `<p class="mock-kicker">INSTALLED BOTS</p><h3 class="mock-title">Bots</h3><label class="bot-search"><svg viewBox="0 0 12 12" aria-hidden="true"><circle cx="5" cy="5" r="3.4"></circle><line x1="7.6" y1="7.6" x2="11" y2="11"></line></svg><input type="text" placeholder="Search bots" aria-label="Search bots"></label><div class="bot-list">${Object.entries(bots).map(([id,x])=>`<button class="bot-tile ${id===selectedBot?'active':''}" data-bot="${id}"><i>${x.name[0]}</i><span><b>${x.name}</b><small>${x.copy}</small></span><em>›</em></button>`).join('')}</div><div class="bot-detail"><small>${bot.label}</small><b>${bot.name} Bot</b><span>${bot.copy}</span><code>${bot.tools}</code></div>`}
function appMarkup(s){return mobileTab==='space'?spaceMarkup(s):mobileTab==='bots'?botsMarkup():inboxMarkup(s)}
window.selectMobileTab=tab=>{mobileTab=tab;drawLab()};window.selectBot=id=>{selectedBot=id;drawLab()};function drawMobileNav(){document.querySelectorAll('[data-mobile-tab]').forEach(b=>{const active=b.dataset.mobileTab===mobileTab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');b.onclick=()=>window.selectMobileTab(b.dataset.mobileTab)});document.querySelectorAll('[data-bot]').forEach(b=>b.onclick=()=>window.selectBot(b.dataset.bot));const bs=document.querySelector('.bot-search input');if(bs)bs.oninput=()=>{const q=bs.value.trim().toLowerCase();document.querySelectorAll('.bot-tile').forEach(b=>{b.style.display=b.textContent.toLowerCase().includes(q)?'':'none'})}}
function drawLab(){const f=flows[scenario],s=f.steps[flowStep];$('#app-owner').textContent=mobileTab==='bots'?'Muthu · Owner':f.owner;$('#lab-progress').innerHTML=f.steps.map((x,i)=>`<span class="lab-step ${i===flowStep?'active':i<flowStep?'done':''}"><i>${i<flowStep?'✓':i+1}</i>${x[0]}</span>`).join('');$('#app-screen').innerHTML=appMarkup(s);drawMobileNav();$('#trace-status').textContent=s[0];$('#trace-kind').textContent=s[1];$('#trace-title').textContent=s[0];$('#trace-copy').textContent=s[2];$('#trace-flow').innerHTML=s[3].map((x,i)=>`<div class="trace-node ${i===1?'on':''}"><b>${x}</b><small>${i===0?'input':i===1?'current work':'durable result'}</small></div>${i<s[3].length-1?'<i>›</i>':''}`).join('');$('#trace-note').innerHTML=`<b>Boundary:</b> ${s[4]}`;$('#lab-count').textContent=`${flowStep+1} / ${f.steps.length}`;$('#lab-step').textContent=s[0];$('#lab-back').disabled=flowStep===0;$('#lab-back').style.opacity=flowStep===0?.35:1;$('#lab-next').innerHTML=flowStep===f.steps.length-1?'Restart <b>↺</b>':`${s[9]} <b>→</b>`;document.querySelector('.lab-workbench').animate([{opacity:.55,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:240})}
document.querySelectorAll('.scenario').forEach(b=>b.onclick=()=>{scenario=b.dataset.scenario;flowStep=0;document.querySelectorAll('.scenario').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)});drawLab()});$('#lab-next').onclick=()=>{flowStep=flowStep===flows[scenario].steps.length-1?0:flowStep+1;drawLab()};$('#lab-back').onclick=()=>{if(flowStep){flowStep--;drawLab()}};
const harness={context:['Context','A small, labelled package of permitted Records, messages, the current Run checkpoint, and previous Tool results. It is rebuilt from current truth when work resumes.'],skills:['Skills','Instructions and methods for this kind of step: how to classify a complaint, draft a reply, or reconcile a provider. A Skill guides work but grants no authority.'],executor:['Executor','Code for known rules, an LLM for interpretation and drafts, or a human for judgement and approval. The published step chooses which executor may act.'],tools:['Tools','Explicit callable interfaces. Read Tools return permitted projections. Action Tools submit registered proposals to the Gateway. A prompt cannot add Tools.'],limits:['Limits','Fixed tools, turns, runtime, cost, retry policy, and stopping condition. These keep one agent step bounded and recoverable.'],output:['Output','A read result or a schema-checked proposal. Model text alone never becomes a shared Record, payment, message, or permission.']};function explainHarness(k){document.querySelectorAll('[data-harness]').forEach(b=>b.classList.toggle('active',b.dataset.harness===k));$('#harness-explain').innerHTML=`<b>${harness[k][0]}</b><p>${harness[k][1]}</p>`}document.querySelectorAll('[data-harness]').forEach(b=>b.onclick=()=>explainHarness(b.dataset.harness));
const components={worker:['Cloudflare Worker API','The front door for HTTP, identity, tenant routing, and public endpoints. It sends reads to the Read Service and writes to the Action Gateway.','ENTRY'],read:['Read Service','Builds permitted views from the authorized tenant: app screens, Inbox, metrics, Record details, and model context.','READ'],gateway:['Action Gateway','The only acceptance boundary for authoritative changes: authenticate, authorize, validate, replay, version-check, and transact.','CONTROL'],turso:['Turso tenant database','One isolated database per work workspace or private identity. It holds Records, Runs, Events, Definitions, Effect Requests, and consumer progress.','STATE'],d1:['D1 control','Identity, workspace membership, tenant routing, connector metadata, and command ledger. Control changes use their own registered Actions.','CONTROL'],router:['Event router + Queue','Routes committed Event IDs to consumers, wakes Runs, and schedules external-effect work. Consumer cursors and dedupe make repeated wakes safe.','WAKE'],runner:['Run engine + Runner','Claims durable Runs, derives one declared transition, and executes one bounded code, model, or human step. The Run row remains authoritative.','EXECUTE'],r2:['R2 + device SQLite','R2 stores immutable large files and releases. Device SQLite keeps permitted cache, drafts, and pending offline commands; reconnect still passes through the Gateway.','FILES + OFFLINE']};function drawSystem(k){$('#system-map').innerHTML=Object.entries(components).map(([id,x])=>`<button class="component ${id===k?'active':''}" data-component="${id}"><small>${x[2]}</small><b>${x[0]}</b></button>`).join('');$('#system-explain').innerHTML=`<b>${components[k][0]}:</b> ${components[k][1]}`;document.querySelectorAll('.component').forEach(b=>b.onclick=()=>drawSystem(b.dataset.component))}
drawLab();explainHarness('executor');drawSystem('gateway');
