import Ionicons from '@expo/vector-icons/Ionicons';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { harness, type HarnessRecord } from '@/lib/harness';

type Tab = 'work' | 'inbox' | 'records'; type DraftKind = 'record' | 'task';
interface Props { scope: string; workspaceName: string; onOpenWorkspaceSwitcher: () => void; }
const titleCase = (value: string) => value.replace(/[_-]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function HarnessWorkspaceCanvas({ scope, workspaceName, onOpenWorkspaceSwitcher }: Props) {
  const insets = useSafeAreaInsets();
  const [tab, setTab] = useState<Tab>('work'); const [records, setRecords] = useState<HarnessRecord[]>([]); const [tasks, setTasks] = useState<HarnessRecord[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [compose, setCompose] = useState(false); const [kind, setKind] = useState<DraftKind>('record'); const [title, setTitle] = useState(''); const [recordType, setRecordType] = useState('contact'); const [saving, setSaving] = useState(false);
  const reload = useCallback(async () => { setError(''); try { const [nextRecords, nextInbox] = await Promise.all([harness.records(scope), harness.inbox(scope)]); setRecords(nextRecords.records); setTasks(nextInbox.tasks); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load workspace.'); } finally { setLoading(false); } }, [scope]);
  const retryWorkspace = async () => { setLoading(true); setError(''); try { await harness.createWorkspace(workspaceName, scope); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not provision workspace.'); setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => { void reload(); }, 0); return () => clearTimeout(timer); }, [reload]);
  const save = async () => { const clean = title.trim(); if (!clean || saving) return; setSaving(true); try { if (kind === 'task') await harness.createTask(scope, clean); else await harness.createRecord(scope, { type: recordType.trim().toLowerCase() || 'record', title: clean }); setCompose(false); setTitle(''); await reload(); } catch (cause) { Alert.alert('Could not save', cause instanceof Error ? cause.message : 'Try again.'); } finally { setSaving(false); } };
  const complete = async (task: HarnessRecord) => { try { await harness.completeTask(scope, task.id); await reload(); } catch (cause) { Alert.alert('Could not complete task', cause instanceof Error ? cause.message : 'Try again.'); } };
  return <View style={styles.page}>
    <View style={[styles.header, { paddingTop: insets.top }]}><TouchableOpacity onPress={onOpenWorkspaceSwitcher} style={styles.workspace}><Text numberOfLines={1} style={styles.workspaceName}>{workspaceName}</Text><Ionicons name="chevron-down" size={16} color="#5f6368" /></TouchableOpacity><View style={styles.tabs}>{(['work', 'inbox', 'records'] as Tab[]).map((item) => <TouchableOpacity key={item} onPress={() => setTab(item)} style={styles.tab}><Text style={[styles.tabText, tab === item && styles.tabActive]}>{item === 'work' ? 'Work' : titleCase(item)}</Text></TouchableOpacity>)}</View></View>
    <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 32 }]}>{error ? <Pressable style={styles.error} onPress={() => void retryWorkspace()}><Text style={styles.errorText}>{error} Tap to retry.</Text></Pressable> : null}{loading ? <View style={styles.center}><ActivityIndicator color="#1a73e8" /></View> : <>{tab === 'work' && <><Text style={styles.heading}>Next work</Text>{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} onComplete={complete} />) : <Empty text="No tasks waiting for you." />}</>}{tab === 'inbox' && <>{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} onComplete={complete} />) : <Empty text="You're all caught up." />}</>}{tab === 'records' && <>{records.length ? records.map((record) => <View key={record.id} style={styles.record}><View style={styles.recordCopy}><Text style={styles.recordTitle}>{record.title}</Text><Text style={styles.recordDetail}>{titleCase(record.type)} · {titleCase(record.state)}</Text></View></View>) : <Empty text="No records yet." />}</>}</>}</ScrollView>
    <TouchableOpacity style={styles.fab} onPress={() => setCompose(true)} accessibilityLabel="Create work"><Ionicons name="add" size={27} color="#fff" /></TouchableOpacity>
    <Modal visible={compose} transparent animationType="fade" onRequestClose={() => setCompose(false)}><View style={styles.overlay}><View style={styles.sheet}><Text style={styles.sheetTitle}>Create</Text><View style={styles.switch}>{(['record', 'task'] as DraftKind[]).map((value) => <TouchableOpacity key={value} style={[styles.switchButton, kind === value && styles.switchSelected]} onPress={() => setKind(value)}><Text style={styles.switchText}>{titleCase(value)}</Text></TouchableOpacity>)}</View>{kind === 'record' ? <TextInput value={recordType} onChangeText={setRecordType} placeholder="Type, for example contact" style={styles.input} /> : null}<TextInput autoFocus value={title} onChangeText={setTitle} placeholder={kind === 'task' ? 'What needs doing?' : 'Record name'} style={styles.input} onSubmitEditing={() => void save()} /><View style={styles.actions}><TouchableOpacity onPress={() => setCompose(false)}><Text style={styles.cancel}>Cancel</Text></TouchableOpacity><TouchableOpacity disabled={saving || !title.trim()} onPress={() => void save()}><Text style={[styles.save, (!title.trim() || saving) && styles.disabled]}>{saving ? 'Saving' : 'Save'}</Text></TouchableOpacity></View></View></View></Modal>
  </View>;
}
function TaskRow({ task, onComplete }: { task: HarnessRecord; onComplete: (task: HarnessRecord) => void }) { return <View style={styles.task}><View style={styles.recordCopy}><Text style={styles.recordTitle}>{task.title}</Text><Text style={styles.recordDetail}>Assigned work</Text></View><TouchableOpacity onPress={() => void onComplete(task)} style={styles.complete} accessibilityLabel={`Complete ${task.title}`}><Ionicons name="checkmark" size={18} color="#1a73e8" /></TouchableOpacity></View>; }
function Empty({ text }: { text: string }) { return <Text style={styles.empty}>{text}</Text>; }
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#fff'},header:{borderBottomWidth:1,borderColor:'#e8eaed',backgroundColor:'#fff'},workspace:{height:52,paddingHorizontal:24,flexDirection:'row',gap:6,alignItems:'center'},workspaceName:{flexShrink:1,fontSize:20,fontWeight:'800',color:'#202124'},tabs:{flexDirection:'row',paddingHorizontal:24,gap:24},tab:{paddingVertical:12},tabText:{fontSize:15,fontWeight:'600',color:'#5f6368'},tabActive:{color:'#1a73e8'},content:{padding:24},center:{minHeight:160,justifyContent:'center',alignItems:'center'},heading:{fontSize:24,fontWeight:'800',color:'#202124',marginBottom:12},task:{minHeight:68,borderTopWidth:StyleSheet.hairlineWidth,borderColor:'#e8eaed',flexDirection:'row',alignItems:'center',gap:14},record:{minHeight:64,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#e8eaed',justifyContent:'center'},recordCopy:{flex:1},recordTitle:{fontSize:16,fontWeight:'700',color:'#202124'},recordDetail:{fontSize:13,color:'#70757a',marginTop:3},complete:{width:38,height:38,borderWidth:1,borderColor:'#d2e3fc',borderRadius:19,alignItems:'center',justifyContent:'center'},empty:{color:'#70757a',fontSize:16,paddingVertical:18},error:{backgroundColor:'#fce8e6',borderRadius:8,padding:12,marginBottom:14},errorText:{color:'#a50e0e'},fab:{position:'absolute',right:24,bottom:26,width:56,height:56,borderRadius:28,backgroundColor:'#1a73e8',alignItems:'center',justifyContent:'center',elevation:3},overlay:{flex:1,backgroundColor:'#0005',justifyContent:'center',padding:24},sheet:{backgroundColor:'#fff',borderRadius:14,padding:22},sheetTitle:{fontSize:22,fontWeight:'800',color:'#202124',marginBottom:16},switch:{flexDirection:'row',gap:8,marginBottom:12},switchButton:{paddingHorizontal:13,paddingVertical:8,borderRadius:16,borderWidth:1,borderColor:'#dadce0'},switchSelected:{backgroundColor:'#e8f0fe',borderColor:'#1a73e8'},switchText:{color:'#202124',fontWeight:'700'},input:{borderBottomWidth:1,borderColor:'#dadce0',fontSize:16,color:'#202124',paddingVertical:12,marginBottom:10},actions:{flexDirection:'row',justifyContent:'flex-end',gap:24,marginTop:10},cancel:{color:'#5f6368',fontWeight:'700'},save:{color:'#1a73e8',fontWeight:'800'},disabled:{opacity:.45} });
