import Ionicons from '@expo/vector-icons/Ionicons';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Modal, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { tar, type HarnessDefinition, type HarnessRecord } from '@/lib/tar';

export interface WorkflowRunContext { runId?: string; botId: string; workflowId: string; stepId: string; recordId?: string | null; }
interface Props { scope: string; run: WorkflowRunContext | null; definitions: HarnessDefinition[]; onClose: () => void; onFinished: () => void; }
function text(value: unknown): string { return typeof value === 'string' ? value.trim() : ''; }
function label(field: string): string { return field === 'related_to' ? 'Related to' : field.replace(/[_-]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }

function ComposeField({ field, value, editable, focused, autoFocus, onFocus, onBlur, onChange }: { field: string; value: string; editable: boolean; focused: boolean; autoFocus: boolean; onFocus: () => void; onBlur: () => void; onChange: (value: string) => void }) {
  return <View style={[styles.fieldRow, focused && styles.fieldFocused]}><Text numberOfLines={1} style={styles.fieldLabel}>{label(field)}</Text><TextInput autoFocus={autoFocus} value={value} onChangeText={onChange} editable={editable} onFocus={onFocus} onBlur={onBlur} placeholder={focused ? '' : undefined} autoCapitalize={field === 'email' ? 'none' : 'sentences'} keyboardType={field === 'email' ? 'email-address' : field.includes('phone') ? 'phone-pad' : 'default'} style={styles.input} /></View>;
}

export default function WorkflowFlow({ scope, run, definitions, onClose, onFinished }: Props) {
  const insets = useSafeAreaInsets(); const [values, setValues] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [focusedField, setFocusedField] = useState(''); const [organizations, setOrganizations] = useState<HarnessRecord[]>([]); const [pickingOrganization, setPickingOrganization] = useState(false);
  const current = useMemo(() => {
    if (!run) return null;
    const bot = definitions.find((definition) => definition.id === run.botId); const workflows = Array.isArray(bot?.body.workflows) ? bot.body.workflows as Record<string, unknown>[] : []; const workflow = workflows.find((item) => text(item.id) === run.workflowId); const steps = Array.isArray(workflow?.steps) ? workflow.steps as Record<string, unknown>[] : []; const step = steps.find((item) => text(item.id) === run.stepId) || steps[0];
    return bot && workflow && step ? { bot, workflow, step } : null;
  }, [definitions, run]);
  const fields = useMemo(() => { const card = current?.step.card && typeof current.step.card === 'object' && !Array.isArray(current.step.card) ? current.step.card as Record<string, unknown> : {}; return Array.isArray(card.fields) ? card.fields.map(text).filter(Boolean).slice(0, 16) : []; }, [current]);
  const screenTitle = current ? text(current.workflow.title) || current.bot.name : 'Workflow';
  useEffect(() => { if (!run || !fields.includes('organization')) return; void tar.harness.records(scope, 'organizations').then((result) => setOrganizations(result.records)).catch(() => setOrganizations([])); }, [fields, run, scope]);
  const submit = async () => {
    if (!run || !current || saving) return;
    const actions = Array.isArray(current.step.actions) ? current.step.actions.map(String) : []; const createsRecord = actions.includes('database.record.create'); const cleaned = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value.trim()]).filter(([, value]) => Boolean(value)));
    if (createsRecord && fields.some((field) => field === 'name' || field === 'title') && !cleaned.name && !cleaned.title) { Alert.alert('Enter a name', 'This record needs a name before it can be saved.'); return; }
    const startedAt = Date.now(); console.info('[TarPerf][workflow-save] start', JSON.stringify({ workflowId: run.workflowId, stepId: run.stepId, createsRecord })); setSaving(true);
    try { const recordId = run.recordId || undefined; if (createsRecord && !recordId) { const recordType = text(current.workflow.recordType) || text(current.workflow.artifactId); const recordTitle = cleaned.name || cleaned.title || cleaned[fields[0] || '']; if (!recordType || !recordTitle) throw new Error('This Workflow needs a record type and title.'); await tar.harness.command(scope, { action: 'run.submit', ...(run.runId ? { target: run.runId } : {}), botId: run.botId, workflowId: run.workflowId, record: { type: recordType, title: recordTitle, data: cleaned }, data: cleaned }); } else await tar.harness.command(scope, { action: run.runId ? 'run.advance' : 'run.submit', ...(run.runId ? { target: run.runId } : {}), botId: run.botId, workflowId: run.workflowId, recordId, data: cleaned }); console.info('[TarPerf][workflow-save] complete', JSON.stringify({ elapsedMs: Date.now() - startedAt, workflowId: run.workflowId, stepId: run.stepId })); onFinished(); } catch (cause) { console.warn('[TarPerf][workflow-save] failed', JSON.stringify({ elapsedMs: Date.now() - startedAt, workflowId: run.workflowId, stepId: run.stepId })); Alert.alert('Could not save', cause instanceof Error ? cause.message : 'Try again.'); } finally { setSaving(false); }
  };
  const selectOrganization = (organization: HarnessRecord) => { setValues((currentValues) => ({ ...currentValues, organization: organization.title })); setPickingOrganization(false); };
  return <Modal visible={Boolean(run)} animationType="slide" presentationStyle="fullScreen" onRequestClose={onClose}>
    <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined} accessibilityLabel={screenTitle}>
      <View style={[styles.toolbar, { paddingTop: insets.top }]}><TouchableOpacity onPress={onClose} accessibilityRole="button" accessibilityLabel="Go back" style={styles.iconButton}><Ionicons name="arrow-back" size={28} color="#202124" /></TouchableOpacity><View style={styles.toolbarSpacer} /><TouchableOpacity accessibilityRole="button" accessibilityLabel="Save" disabled={saving} style={[styles.saveButton, saving && styles.disabled]} onPress={() => void submit()}>{saving ? <ActivityIndicator size="small" color="#1a73e8" /> : <Text style={styles.saveText}>Save</Text>}</TouchableOpacity><View style={styles.iconButton}><Ionicons name="ellipsis-vertical" size={25} color="#202124" /></View></View>
      {!current ? <View style={styles.center}><Text style={styles.error}>This Workflow definition is no longer available.</Text><TouchableOpacity onPress={onClose}><Text style={styles.close}>Close</Text></TouchableOpacity></View> : <ScrollView contentContainerStyle={[styles.form, { paddingBottom: Math.max(insets.bottom, 20) + 120 }]} keyboardShouldPersistTaps="handled">{fields.map((field, index) => field === 'organization' ? <TouchableOpacity key={field} accessibilityRole="button" accessibilityLabel="Select organization" disabled={saving} style={[styles.fieldRow, focusedField === field && styles.fieldFocused]} onPress={() => setPickingOrganization(true)}><Text numberOfLines={1} style={styles.fieldLabel}>Organization</Text><Text numberOfLines={1} style={[styles.selection, !values.organization && styles.selectionPlaceholder]}>{values.organization || (organizations.length ? 'Select organization' : 'No organizations yet')}</Text><Ionicons name="chevron-down" size={20} color="#5f6368" /></TouchableOpacity> : <ComposeField key={field} field={field} value={values[field] || ''} editable={!saving} focused={focusedField === field} autoFocus={index === 0} onFocus={() => setFocusedField(field)} onBlur={() => setFocusedField('')} onChange={(value) => setValues((currentValues) => ({ ...currentValues, [field]: value }))} />)}</ScrollView>}
      <Modal visible={pickingOrganization} transparent animationType="slide" onRequestClose={() => setPickingOrganization(false)}><View style={styles.pickerBackdrop}><View style={[styles.picker, { paddingBottom: Math.max(insets.bottom, 18) }]}><Text style={styles.pickerTitle}>Select organization</Text>{organizations.length ? organizations.map((organization) => <TouchableOpacity key={organization.id} style={styles.pickerRow} onPress={() => selectOrganization(organization)}><Text style={styles.pickerRowTitle}>{organization.title}</Text></TouchableOpacity>) : <Text style={styles.pickerEmpty}>Create an organization first.</Text>}<TouchableOpacity style={styles.cancelButton} onPress={() => setPickingOrganization(false)}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity></View></View></Modal>
    </KeyboardAvoidingView>
  </Modal>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#ffffff' }, toolbar: { minHeight: 104, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, backgroundColor: '#ffffff' }, toolbarSpacer: { flex: 1 }, iconButton: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }, saveButton: { minWidth: 62, height: 48, alignItems: 'center', justifyContent: 'center' }, saveText: { color: '#1a73e8', fontSize: 16, fontWeight: '700' }, form: { paddingTop: 28 }, fieldRow: { minHeight: 67, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#c9c9c9', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 30 }, fieldFocused: {}, fieldLabel: { width: 154, color: '#5f6368', fontSize: 18, fontWeight: '400' }, input: { flex: 1, minHeight: 52, color: '#202124', fontSize: 18, paddingVertical: 0 }, selection: { flex: 1, color: '#202124', fontSize: 16 }, selectionPlaceholder: { color: '#8a8a8a' }, disabled: { opacity: 0.45 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, padding: 28 }, error: { color: '#b3261e', fontSize: 15, textAlign: 'center' }, close: { color: '#1a73e8', fontSize: 15, fontWeight: '700' }, pickerBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, picker: { backgroundColor: '#ffffff', paddingTop: 24 }, pickerTitle: { color: '#202124', fontSize: 20, fontWeight: '700', paddingHorizontal: 24, paddingBottom: 12 }, pickerRow: { minHeight: 56, justifyContent: 'center', paddingHorizontal: 24 }, pickerRowTitle: { color: '#202124', fontSize: 17 }, pickerEmpty: { color: '#5f6368', fontSize: 16, paddingHorizontal: 24, paddingVertical: 18 }, cancelButton: { minHeight: 52, justifyContent: 'center', alignItems: 'flex-end', paddingHorizontal: 24 }, cancelText: { color: '#1a73e8', fontSize: 15, fontWeight: '700' },
});
